name: wishes_repository
description: A repository that handles wish related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  wishes_api:
    path: ../wishes_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.6
  very_good_analysis: ^3.1.0
